Update to latest sonar-python that runs under this infrastructure
Trying to address some false positives that were solved on 1.9+.

Tried to upgrade to newer version on sonar-python but anything
behind 1.9.1.2080 does fail with a java.lang.NoClassDefFoundError,
probably some changes are required at infrastructure level.